package com.jasonharris97.jaysports.presentation.teamDetails.navigation

import com.jasonharris97.jaysports.presentation.core.model.PresentationDestination

sealed interface TeamDetailsPresentationDestination : PresentationDestination
